"use client";

import React, { useEffect, useState } from "react";
import Script from "next/script";

export default function ARPage() {
  const [aframeLoaded, setAframeLoaded] = useState(false);
  const [arjsLoaded, setArjsLoaded] = useState(false);

  const [status, setStatus] = useState("Loading...");
  const [detected, setDetected] = useState(false);

  /*
   * Listen for NFT marker events.
   */
  useEffect(() => {
    if (!arjsLoaded) return;

    const timer = setTimeout(() => {
      const marker = document.querySelector("#flag-marker");

      if (!marker) {
        console.log("Flag marker element not found.");
        setStatus("❌ Marker element not found");
        return;
      }

      console.log("Flag marker element found.");

      const handleFound = () => {
        console.log("FLAG DETECTED");

        setDetected(true);
        setStatus("✅ FLAG DETECTED");
      };

      const handleLost = () => {
        console.log("FLAG LOST");

        setDetected(false);
        setStatus("🔍 SCANNING FOR FLAG...");
      };

      marker.addEventListener("markerFound", handleFound);
      marker.addEventListener("markerLost", handleLost);

      setStatus("🔍 SCANNING FOR FLAG...");

      return () => {
        marker.removeEventListener("markerFound", handleFound);
        marker.removeEventListener("markerLost", handleLost);
      };
    }, 1000);

    return () => {
      clearTimeout(timer);
    };
  }, [arjsLoaded]);

  return (
    <>
      {/* ================================
          GLOBAL STYLES
      ================================= */}

      <style jsx global>{`
        html,
        body {
          margin: 0 !important;
          padding: 0 !important;

          width: 100% !important;
          height: 100% !important;

          overflow: hidden !important;

          background: #000 !important;
        }

        main {
          margin: 0 !important;
          padding: 0 !important;
        }

        /*
         * Camera video generated by AR.js
         */
        video {
          position: fixed !important;

          top: 0 !important;
          left: 0 !important;

          width: 100vw !important;
          height: 100vh !important;

          object-fit: cover !important;

          margin: 0 !important;
          padding: 0 !important;

          z-index: 0 !important;
        }

        /*
         * A-Frame scene
         */
        a-scene {
          position: fixed !important;

          top: 0 !important;
          left: 0 !important;

          width: 100vw !important;
          height: 100vh !important;

          z-index: 1 !important;
        }

        /*
         * A-Frame WebGL canvas
         */
        .a-canvas {
          position: fixed !important;

          top: 0 !important;
          left: 0 !important;

          width: 100vw !important;
          height: 100vh !important;
        }
      `}</style>

      {/* ================================
          LOAD A-FRAME
      ================================= */}

      <Script
        src="https://aframe.io/releases/1.6.0/aframe.min.js"
        strategy="afterInteractive"
        onLoad={() => {
          console.log("A-Frame loaded");

          setAframeLoaded(true);
          setStatus("Loading AR.js...");
        }}
      />

      {/* ================================
          LOAD AR.JS
      ================================= */}

      {aframeLoaded && (
        <Script
          src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"
          strategy="afterInteractive"
          onLoad={() => {
            console.log("AR.js loaded");

            setArjsLoaded(true);
            setStatus("Starting camera...");
          }}
        />
      )}

      {/* ================================
          MAIN
      ================================= */}

      <main
        style={{
          position: "fixed",

          top: 0,
          left: 0,

          width: "100vw",
          height: "100vh",

          overflow: "hidden",

          background: "#000",
        }}
      >
        {/* ================================
            DEBUG STATUS
        ================================= */}

        <div
          style={{
            position: "fixed",

            top: "20px",
            left: "50%",

            transform: "translateX(-50%)",

            zIndex: 99999,

            padding: "12px 18px",

            background: detected
              ? "rgba(0, 150, 0, 0.9)"
              : "rgba(0, 0, 0, 0.8)",

            color: "#fff",

            borderRadius: "8px",

            fontFamily: "Arial, sans-serif",

            fontWeight: "bold",

            fontSize: "14px",

            whiteSpace: "nowrap",

            textAlign: "center",
          }}
        >
          {status}
        </div>

        {/* ================================
            AR SCENE
        ================================= */}

        {aframeLoaded &&
          arjsLoaded &&
          React.createElement(
            "a-scene",
            {
              embedded: true,

              "vr-mode-ui": "enabled: false",

              renderer:
                "logarithmicDepthBuffer: true; antialias: true; alpha: true;",

              arjs: `
                trackingMethod: best;
                sourceType: webcam;
                debugUIEnabled: false;
              `,
            },

            /*
             * =============================
             * FLAG NFT MARKER
             * =============================
             */

            React.createElement(
              "a-nft",
              {
                id: "flag-marker",

                type: "nft",

                url: "/markers/flag",

                smooth: "true",

                smoothCount: "10",

                smoothTolerance: "0.01",

                smoothThreshold: "5",

                /*
                 * IMPORTANT:
                 * This enables markerFound
                 * and markerLost events.
                 */
                emitevents: "true",
              },

              /*
               * =============================
               * RED TEST BOX
               * =============================
               */

              React.createElement("a-box", {
                position: "50 100 0",

                scale: "20 20 20",

                material: `
                  color: red;
                  opacity: 1;
                `,
              })
            ),

            /*
             * =============================
             * CAMERA
             * =============================
             */

            React.createElement("a-entity", {
              camera: "",
            })
          )}
      </main>
    </>
  );
}
